using System.Collections.Generic;
namespace XIVHubCompanion.Collections
{
    public static class HairstyleCatalog
    {
        public class HairstyleEntry
        {
            public uint UnlockLink { get; set; }
            public string Name { get; set; }
            public string Description { get; set; }
            public uint IconId { get; set; }
            public string[] Sources { get; set; }
        }

        public static readonly List<HairstyleEntry> Entries = new List<HairstyleEntry>
        {
            new HairstyleEntry { UnlockLink = 638, Name = "Bun and the Beautiful", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques on pulling one's hair into a perfect bun.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 250104, Sources = new string[] { "Occult Crescent: Expedition Antiquarian - North Horn - 40 Arcane Amulets ", "Occult Crescent: North Horn - Bronze/Silver Coffer" } },
            new HairstyleEntry { UnlockLink = 576, Name = "Shadowhunter Chic", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for emulating the signature look of the hunter formerly known as Gaius van Baelsar.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 250103, Sources = new string[] { "V&C Dungeon: Trisassant - Old Sharlayan - 20 Pieces of Corvosi Brass" } },
            new HairstyleEntry { UnlockLink = 575, Name = "Fit for a Princess", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for pinning your hair in a princess-perfect style. \n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 250102, Sources = new string[] { "Premium: Online Store" } },
            new HairstyleEntry { UnlockLink = 574, Name = "Tail of the Teller", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for a ponytail that suggests a great destiny awaits the wearer, in spite of its simplicity.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 250101, Sources = new string[] { "Premium: Online Store" } },
            new HairstyleEntry { UnlockLink = 573, Name = "Realms-ruffled", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for an artfully accessorized style that appears tousled by otherworldly winds.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 250100, Sources = new string[] { "Premium: Online Store" } },
            new HairstyleEntry { UnlockLink = 552, Name = "Hairscape F", Description = "The realm's premier publication on beauty and fashion, this otherworldly edition of *Modern Aesthetics* covers, in detail, techniques for styling a gravity-defying ponytail reminiscent of Omega-F. May you greet the world in style.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131298, Sources = new string[] { "Premium: Online Store" } },
            new HairstyleEntry { UnlockLink = 551, Name = "Hairscape M", Description = "The realm's premier publication on beauty and fashion, this otherworldly edition of *Modern Aesthetics* covers, in detail, techniques for molding one's coiffure into gravity-defying locks reminiscent of Omega-M. May you greet the world in style.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131299, Sources = new string[] { "Premium: Online Store" } },
            new HairstyleEntry { UnlockLink = 550, Name = "Simple and Clean", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for achieving an eminently unfussy face-framing coiffure.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131297, Sources = new string[] { "Deep Dungeon: 99 Phials of Luminous Oil", "Deep Dungeon: Pilgrim's Traverse - Silver/Gold/Platinum Sack" } },
            new HairstyleEntry { UnlockLink = 539, Name = "Fulsome Forelocks", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for concealing one's visage with a luscious curtain of locks that fall past the eyes.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131296, Sources = new string[] { "Occult Crescent: Expedition Antiquarian - South Horn - 30 Chunks of Sanguinite", "Occult Crescent: South Horn - Silver Coffer" } },
            new HairstyleEntry { UnlockLink = 538, Name = "The Warden", Description = "The realm's premier publication on beauty and fashion, this legendary edition of *Modern Aesthetics* covers, in detail, the cascading coiffure required to emulate the goddess Azeyma Herself.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131295, Sources = new string[] { "Premium: Online Store" } },
            new HairstyleEntry { UnlockLink = 486, Name = "A Half Times Two", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for taming tresses into two perfectly plaited halfbraids, replete with ribbons and all.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131291, Sources = new string[] { "Chaotic Raid: Uah'shepya - Solution Nine - 49 Clouddark Demimateria II", "Chaotic Raid: The Cloud of Darkness (Chaotic)" } },
            new HairstyleEntry { UnlockLink = 489, Name = "Head Hound", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for coaxing one's locks into a rambunctious side braid and ponytail combination.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131294, Sources = new string[] { "Premium: Online Store" } },
            new HairstyleEntry { UnlockLink = 488, Name = "Voidswept Strands", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for achieving a perfectly unbalanced asymmetric bob.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131293, Sources = new string[] { "Premium: Online Store" } },
            new HairstyleEntry { UnlockLink = 487, Name = "Scion Special Issue IV", Description = "The realm's premier publication on beauty and fashion, this limited edition of *Modern Aesthetics* covers, in detail, techniques for emulating the style of G'raha TiaÔöÇdefinitively the dreamiest Scion of the Seventh Dawn, despite what previous editions may purport.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131292, Sources = new string[] { "Premium: Online Store" } },
            new HairstyleEntry { UnlockLink = 485, Name = "Doing the Wave", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for achieving an effortlessly textured bob suitable for all occasions.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131290, Sources = new string[] { "Treasure Hunt: Cenote Ja Ja Gural", "Treasure Hunt: Vault Oneiron" } },
            new HairstyleEntry { UnlockLink = 483, Name = "It Takes Two", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for shaping shorter locks into two feathery, distinct parts that softly frame one's visage.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131289, Sources = new string[] { "Treasure Hunt: Timeworn Br'aaxskin/Gargantuaskin Map" } },
            new HairstyleEntry { UnlockLink = 476, Name = "The Bold and the Braid", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for braiding unruly locks into lineÔöÇwhile allowing others to flow free in defiance of expectation.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to female Hrothgar.", IconId = 131287, Sources = new string[] { "V&C Dungeon: Trisassant - Old Sharlayan - 6 Aloalo Potsherds" } },
            new HairstyleEntry { UnlockLink = 460, Name = "Ambitious Ends", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, styling techniques used to mixed success since the time of the ancients.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to female Hrothgar.", IconId = 131286, Sources = new string[] { "V&C Dungeon: Trisassant - Old Sharlayan - 6 Rokkon Potsherds" } },
            new HairstyleEntry { UnlockLink = 448, Name = "A Close Shave", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for cropping one's locks so as to improve aerodynamics in the face of impending danger, whilst still remaining at the height of trendiness.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to female Hrothgar.", IconId = 131285, Sources = new string[] { "Deep Dungeon: Eureka Orthos - Bronze Sack" } },
            new HairstyleEntry { UnlockLink = 447, Name = "Sharlayan Rebellion", Description = "The realm's premier publication on beauty and fashion, this limited edition of *Modern Aesthetics* covers, in detail, techniques on transforming your style into that of the prominentÔöÇsome would say not prominent *enough*ÔöÇmember of the Scions of the Seventh Dawn, Alisaie Leveilleur.\n* Please note that, while bearing certain similarities, this edition is decidedly *not* a rerun of a previous edition. We thank you for your understanding.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to female Hrothgar.", IconId = 131284, Sources = new string[] { "Premium: Online Store - Brand-new Alisaie's Attire" } },
            new HairstyleEntry { UnlockLink = 442, Name = "Practical Ponytails", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for tying back even the most unruly manes with a minimum of effort.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to female Hrothgar.", IconId = 131283, Sources = new string[] { "Island Sanctuary: 6,000 Seafarer's Cowries" } },
            new HairstyleEntry { UnlockLink = 441, Name = "Tall Tails", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques on tying the perfect high ponytail.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131282, Sources = new string[] { "Island Sanctuary: 6,000 Seafarer's Cowries" } },
            new HairstyleEntry { UnlockLink = 435, Name = "Liberating Locks", Description = "The realm's premier publication on beauty and fashion, this limited edition of *Modern Aesthetics* covers, in detail, unauthorized techniques for assuming the style of Ala Mhigo's fearless leader, Lyse Hext.\n\nUse to unlock a new hairstyle at the aesthetician.\nFits:ÔÖÇ\nUnavailable to female Hrothgar.", IconId = 131775, Sources = new string[] { "Premium: Online Store - Lyse's Leadership Attire" } },
            new HairstyleEntry { UnlockLink = 239, Name = "Clowning Around", Description = "The realm's premier publication on cosmeticsÔöÇas well as dating advice and, for some reason, politicsÔöÇthis copy of *Modern Cosmetics* covers, in detail, techniques for painting an appropriately spooky clown pattern on one's face.\n\nUse to unlock new face paint at the aesthetician.", IconId = 130069, Sources = new string[] { "Event: All Saints' Wake (Jan 2022)", "Premium: Online Store" } },
            new HairstyleEntry { UnlockLink = 419, Name = "Both Ways", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, a hair styling technique which marries a braid and a side ponytail in an exquisite union.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131278, Sources = new string[] { "Bozja: Zadnor Lockbox", "Occult Crescent: South Horn - Silver Coffer" } },
            new HairstyleEntry { UnlockLink = 421, Name = "Scanning for Style", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for attaining an uncannily effortless lookÔöÇlike that of your android acquaintance 9S.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131280, Sources = new string[] { "Raid: The Tower at Paradigm's Breach" } },
            new HairstyleEntry { UnlockLink = 420, Name = "Battle-ready Bobs", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for shaping an uncannily perfect bobÔöÇlike that of your android acquaintance 2B.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131279, Sources = new string[] { "Raid: The Tower at Paradigm's Breach" } },
            new HairstyleEntry { UnlockLink = 66, Name = "Early to Rise", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for weaving a simple-yet-elegant braid that can be employed by even those who are not yet fully awake.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131276, Sources = new string[] { "Bozja: Delubrum Reginae", "Bozja: Resistance supplier - Zadnor - 5 Bozjan Gold Coins and 30 Bozjan Platinum Coins", "Occult Crescent: South Horn - Silver Coffer" } },
            new HairstyleEntry { UnlockLink = 67, Name = "Sharlayan Studies", Description = "The realm's premier publication on beauty and fashion, this limited edition of *Modern Aesthetics* covers, in detail, techniques on transforming yourself into the prominentÔöÇsome would say *too* prominentÔöÇmember of the Scions of the Seventh Dawn, Alphinaud Leveilleur.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131277, Sources = new string[] { "Premium: Online Store - Brand-new Alphinaud's Attire" } },
            new HairstyleEntry { UnlockLink = 281, Name = "Wind Caller", Description = "The realm's premier publication on beauty and fashion, this limited edition of *Modern Aesthetics* covers, in detail, feathering and styling techniques to achieve the windswept look of a legendary Vartan warrior.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to female Hrothgar.", IconId = 131275, Sources = new string[] { "Bozja: 150 Bozjan Clusters", "Occult Crescent: South Horn - Bronze/Silver Coffer" } },
            new HairstyleEntry { UnlockLink = 280, Name = "Saintly Style", Description = "The realm's premier publication on beauty and fashion, this limited edition of *Modern Aesthetics* covers, in detail, shaping and feathering techniques for imitating the *unique* look of an Ishgardian saint of eld.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131274, Sources = new string[] { "Skybuilders: Enie - The Firmament - 1,800 Skybuilders' Scrips", "Skybuilders: F├¬te Present", "Cosmic Exploration: Silver/Gold Ancient Record - Auxesia" } },
            new HairstyleEntry { UnlockLink = 72, Name = "Controlled Chaos", Description = "The realm's premier publication on beauty and fashion, this limited edition of *Modern Aesthetics* covers, in detail, trimming and coiffing techniques for an attractively asymmetrical look that's a cut above the ordinary.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131273, Sources = new string[] { "Skybuilders: Enie - The Firmament - 1,800 Skybuilders' Scrips", "Skybuilders: F├¬te Present", "Cosmic Exploration: Silver/Gold Ancient Record - Oizys" } },
            new HairstyleEntry { UnlockLink = 79, Name = "Modern Legend", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques on styling oneself to resemble the hero of the world's oldest fable.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to female Hrothgar.", IconId = 131272, Sources = new string[] { "Skybuilders: Enie - The Firmament - 1,800 Skybuilders' Scrips", "Skybuilders: F├¬te Present", "Cosmic Exploration: Silver/Gold Ancient Record - Oizys" } },
            new HairstyleEntry { UnlockLink = 413, Name = "Great Lengths", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for keeping long hair neat and sleek.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131271, Sources = new string[] { "Gold Saucer: 30,000 MGP" } },
            new HairstyleEntry { UnlockLink = 231, Name = "Lucian Locks", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques on becoming a suitably windswept protagonist.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to Hrothgar.", IconId = 131269, Sources = new string[] { "Event: Final Fantasy XV Collaboration" } },
            new HairstyleEntry { UnlockLink = 397, Name = "Form and Function", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for weaving a simple-yet-elegant braided headband.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to female Hrothgar.", IconId = 131266, Sources = new string[] { "Eureka: Happy Bunny Lockbox - Eureka Pyros", "Occult Crescent: South Horn - Bronze Coffer" } },
            new HairstyleEntry { UnlockLink = 230, Name = "Lexen-tails", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for imitating the Lexentale siblings' signature stage-ready styles.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to female Hrothgar.", IconId = 131268, Sources = new string[] { "Gold Saucer: 50,000 MGP" } },
            new HairstyleEntry { UnlockLink = 399, Name = "Strife", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques on becoming the most memorable of all protagonists.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to Hrothgar.", IconId = 131265, Sources = new string[] { "Other: Community Events Reward" } },
            new HairstyleEntry { UnlockLink = 398, Name = "Styled for Hire", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for trimming and coiffing one's way to the dashing look that's in vogue amongst sellswords across the Three Great Continents.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131267, Sources = new string[] { "PvP: 18,000 Wolf Marks" } },
            new HairstyleEntry { UnlockLink = 267, Name = "Gyr Abanian Plait", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques on braiding hair in the traditional Ala Mhigan fashionÔöÇa style that was popular until the imperial invasion.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to female Hrothgar.", IconId = 131263, Sources = new string[] { "Deep Dungeon: Heaven-on-High - Silver Sack" } },
            new HairstyleEntry { UnlockLink = 268, Name = "Fashionably Feathered", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques for styling short hair using only a razor (and copious amounts of wax).\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131264, Sources = new string[] { "PvP: 18,000 Wolf Marks" } },
            new HairstyleEntry { UnlockLink = 338, Name = "Master & Commander", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques on imitating Ishgard's Lord Commander AymericÔöÇrecently voted by *Modern Aesthetics* readers the realm's dreamiest temple knight.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to Hrothgar.", IconId = 131256, Sources = new string[] { "Premium: Online Store - Aymeric's Attire" } },
            new HairstyleEntry { UnlockLink = 337, Name = "Rainmaker", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* is a compilation of festive stylings for any occasion.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131255, Sources = new string[] { "Gold Saucer: 5,000 MGP" } },
            new HairstyleEntry { UnlockLink = 302, Name = "Samsonian Locks", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, methods for styling longer hair.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to female Hrothgar.", IconId = 131252, Sources = new string[] { "Deep Dungeon: The Palace of the Dead - Bronze/Iron/Silver Sack" } },
            new HairstyleEntry { UnlockLink = 322, Name = "Scion Special Issue III", Description = "The realm's premier publication on beauty and fashion, this limited edition of *Modern Aesthetics* covers, in detail, techniques on transforming yourself into the Scions of the Seventh Dawn's enigmatic healer, Y'shtola.\n\nUse to unlock a new hairstyle at the aesthetician.\nFits: ÔÖÇ (excepting Hrothgar)", IconId = 131742, Sources = new string[] { "Premium: Online Store - Y'shtola's Modish Attire" } },
            new HairstyleEntry { UnlockLink = 321, Name = "Scion Special Issue II", Description = "The realm's premier publication on beauty and fashion, this limited edition of *Modern Aesthetics* covers, in detail, techniques on transforming yourself into ThancredÔöÇthe dreamiest Scion of the Seventh Dawn.\n\nUse to unlock a new hairstyle at the aesthetician.\nFits: ÔÖé (excepting Hrothgar)", IconId = 131545, Sources = new string[] { "Premium: Online Store - Thancred's Modish Attire" } },
            new HairstyleEntry { UnlockLink = 303, Name = "Pulse", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques on becoming the ultimate enigmatic protagonist.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131221, Sources = new string[] { "Event: Final Fantasy XIII Collaboration", "Premium: Online Store - Snow/Lightning's Attire" } },
            new HairstyleEntry { UnlockLink = 290, Name = "Scion Special Issue", Description = "The realm's premier publication on beauty and fashion, this limited edition of *Modern Aesthetics* covers, in detail, techniques on transforming yourself into Scions of the Seventh Dawn Antecedent Minfilia.\n\nUse to unlock a new hairstyle at the aesthetician.\nFits: ÔÖÇ (excepting Hrothgar)", IconId = 131732, Sources = new string[] { "Premium: Online Store - Minfilia's Attire" } },
            new HairstyleEntry { UnlockLink = 287, Name = "Curls", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques on crafting a perfect dome of tight curls.\n\nUse to unlock a new hairstyle at the aesthetician.\nUnavailable to female Hrothgar.", IconId = 131236, Sources = new string[] { "Gold Saucer: 9,600 MGP" } },
            new HairstyleEntry { UnlockLink = 286, Name = "Adventure", Description = "The realm's premier publication on beauty and fashion, this limited edition of *Modern Aesthetics* covers, in detail, a hair styling technique submitted by one of the realm's readers.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131237, Sources = new string[] { "Gold Saucer: 14 MGP" } },
            new HairstyleEntry { UnlockLink = 243, Name = "Ponytails", Description = "The realm's premier publication on beauty and fashion, this specific copy of *Modern Aesthetics* covers, in detail, techniques on tying the perfect ponytail.\n\nUse to unlock a new hairstyle at the aesthetician.", IconId = 131230, Sources = new string[] { "Gold Saucer: 8,000 MGP" } },
            new HairstyleEntry { UnlockLink = 228, Name = "Eternal Bonding", Description = "", IconId = 131220, Sources = new string[] { "Premium: Ceremony of Eternal Bonding" } },
            new HairstyleEntry { UnlockLink = 227, Name = "A Wicked Wake", Description = "The realm's premier publication on cosmeticsÔöÇas well as dating advice and, for some reason, politicsÔöÇthis copy of *Modern Cosmetics* covers, in detail, techniques for painting an appropriately spooky All Saints' Wake pattern on one's cheek.\n\nUse to unlock new face paint at the aesthetician.", IconId = 130028, Sources = new string[] { "Event: All Saints' Wake (2014)", "Premium: Online Store" } },
        };
    }
}
